// Batangas Province locations extracted from AllLocationsPossible.json
// Region IV-A (CALABARZON) - Batangas Province

export const BATANGAS_LOCATIONS = {
  "AGONCILLO": [
    "ADIA", "BAGONG SIKAT", "BALANGON", "BANGIN", "BANYAGA", "BARIGON",
    "BILIBINWANG", "CORAL NA MUNTI", "GUITNA", "MABINI", "PAMIGA",
    "PANHULAN", "PANSIPIT", "POBLACION", "POOK", "SAN JACINTO",
    "SAN TEODORO", "SANTA CRUZ", "SANTO TOMAS", "SUBIC IBABA", "SUBIC ILAYA"
  ],
  "ALITAGTAG": [
    "BALAGBAG", "CONCEPCION", "CONCORDIA", "DALIPIT EAST", "DALIPIT WEST",
    "DOMINADOR EAST", "DOMINADOR WEST", "MUNLAWIN NORTE", "MUNLAWIN SUR",
    "MUZON PRIMERO", "MUZON SEGUNDO", "PINAGKURUSAN", "PING-AS",
    "POBLACION EAST", "POBLACION WEST", "SAN JOSE", "SAN JUAN", "SANTA CRUZ", "TADLAC"
  ],
  "BALAYAN": [
    "BACLARAN", "BARANGAY 1 (POB.)", "BARANGAY 2 (POB.)", "BARANGAY 3 (POB.)",
    "BARANGAY 4 (POB.)", "BARANGAY 5 (POB.)", "BARANGAY 6 (POB.)", "BARANGAY 7 (POB.)",
    "BARANGAY 8 (POB.)", "BARANGAY 9 (POB.)", "BARANGAY 10 (POB.)", "BARANGAY 11 (POB.)",
    "BARANGAY 12 (POB.)", "CALAN", "CALOOCAN", "CALZADA", "CANDA", "CARENAHAN",
    "CAYBUNGA", "CAYPONCE", "DALIG", "DAO", "DILAO", "DUHATAN", "DURUNGAO",
    "GIMALAS", "GUMAMELA", "LAGNAS", "LANATAN", "LANGGANGAN", "LUCBAN POOK",
    "LUCBAN PUTOL", "MAGABE", "MALALAY", "MUNTING TUBIG", "NAVOTAS",
    "PALIKPIKAN", "PATUGO", "POOC", "SAMBAT", "SAMPAGA", "SAN JUAN",
    "SAN PIRO", "SANTOL", "SUKOL", "TACTAC", "TALUDTUD", "TANGGOY"
  ],
  "BALETE": [
    "ALANGILAN", "CALAWIT", "LOOC", "MAGAPI", "MAKINA", "MALABANAN",
    "PALIGAWAN", "PALSARA", "POBLACION", "SALA", "SAMPALOCAN",
    "SAN SEBASTIAN", "SOLIS"
  ],
  "BATANGAS CITY": [
    "ALANGILAN", "BALAGTAS", "BALETE", "BANABA CENTER", "BANABA IBABA",
    "BANABA KANLURAN", "BANABA SILANGAN", "BARANGAY 1 (POB.)", "BARANGAY 2 (POB.)",
    "BARANGAY 3 (POB.)", "BARANGAY 4 (POB.)", "BARANGAY 5 (POB.)", "BARANGAY 6 (POB.)",
    "BARANGAY 7 (POB.)", "BARANGAY 8 (POB.)", "BARANGAY 9 (POB.)", "BARANGAY 10 (POB.)",
    "BARANGAY 11 (POB.)", "BARANGAY 12 (POB.)", "BARANGAY 13 (POB.)", "BARANGAY 14 (POB.)",
    "BARANGAY 15 (POB.)", "BARANGAY 16 (POB.)", "BARANGAY 17 (POB.)", "BARANGAY 18 (POB.)",
    "BARANGAY 19 (POB.)", "BARANGAY 20 (POB.)", "BARANGAY 21 (POB.)", "BARANGAY 22 (POB.)",
    "BARANGAY 23 (POB.)", "BARANGAY 24 (POB.)", "BILOGO", "BOLBOK", "BUKAL",
    "CALICANTO", "CATANDALA", "CONCEPCION", "CONDE ITAAS", "CONDE LABAK",
    "CUTA", "DALIG", "DELA PAZ", "DELA PAZ PULOT APLAYA", "DELA PAZ PULOT ITAAS",
    "DOMOCLAY", "DUMANTAY", "GULOD ITAAS", "GULOD LABAK", "HALIGUE KANLURAN",
    "HALIGUE SILANGAN", "ILIHAN", "KUMBA", "KUMINTANG IBABA", "KUMINTANG ILAYA",
    "LIBJO", "LIPONPON, ISLA VERDE", "MAAPAS", "MABACONG (MATOCO)",
    "MAHABANG DAHILIG", "MAHABANG PARANG", "MAHACOT KANLURAN", "MAHACOT SILANGAN",
    "MALALIM", "MALIBAYO", "MALITAM", "MARUCLAP", "PAGKILATAN",
    "PAHARANG KANLURAN", "PAHARANG SILANGAN", "PALLOCAN KANLURAN", "PALLOCAN SILANGAN",
    "PINAMUCAN", "PINAMUCAN IBABA", "PINAMUCAN SILANGAN", "SAMPAGA",
    "SAN AGAPITO, ISLA VERDE", "SAN AGUSTIN KANLURAN, ISLA VERDE",
    "SAN AGUSTIN SILANGAN, ISLA VERDE", "SAN ANDRES, ISLA VERDE",
    "SAN ANTONIO, ISLA VERDE", "SAN ISIDRO", "SAN JOSE SICO", "SAN MIGUEL",
    "SAN PEDRO", "SANTA CLARA", "SANTA RITA APLAYA", "SANTA RITA KARSADA",
    "SANTO DOMINGO", "SANTO NIÑO", "SIMLONG", "SIRANG LUPA", "SOROSORO IBABA",
    "SOROSORO ILAYA", "SOROSORO KARSADA", "TABANGAO AMBULONG",
    "TABANGAO APLAYA (TABANGAO PROPER)", "TABANGAO DAO", "TALAHIB PANDAYAN",
    "TALAHIB PAYAPA", "TALUMPOK KANLURAN", "TALUMPOK SILANGAN", "TINGA ITAAS",
    "TINGA LABAK", "TULO", "WAWA"
  ],
  "BAUAN": [
    "ALAGAO", "APLAYA", "AS-IS", "BAGONG SILANG", "BAGUILAWA", "BALAYONG",
    "BARANGAY I (POB.)", "BARANGAY II (POB.)", "BARANGAY III (POB.)",
    "BARANGAY IV (POB.)", "BOLO", "COLVO", "CUPANG", "DURUNGAO", "GULIBAY",
    "INICBULAN", "LOCLOC", "MAGALANG-GALANG", "MALINDIG", "MANALUPONG",
    "MANGHINAO PROPER", "MANGHINAO UNO", "NEW DANGLAYAN", "ORENSE", "PITUGO",
    "RIZAL", "SAMPAGUITA", "SAN AGUSTIN", "SAN ANDRES PROPER", "SAN ANDRES UNO",
    "SAN DIEGO", "SAN MIGUEL", "SAN PABLO", "SAN PEDRO", "SAN ROQUE",
    "SAN TEODORO", "SAN VICENTE", "SANTA MARIA", "SANTO DOMINGO", "SINALA"
  ],
  "CALACA": [
    "BACLAS", "BAGONG TUBIG", "BALIMBING", "BAMBANG", "BARANGAY 1 (POB.)",
    "BARANGAY 2 (POB.)", "BARANGAY 3 (POB.)", "BARANGAY 4 (POB.)",
    "BARANGAY 5 (POB.)", "BARANGAY 6 (POB.)", "BISAYA", "CAHIL", "CALANTAS",
    "CALUANGAN", "CAMASTILISAN", "CORAL NI BACAL", "CORAL NI LOPEZ (SUGOD)",
    "DACANLAO", "DILA", "LOMA", "LUMBANG CALZADA", "LUMBANG NA BATA",
    "LUMBANG NA MATANDA", "MADALUNOT", "MAKINA", "MATIPOK", "MUNTING CORAL",
    "NIYUGAN", "PANTAY", "PUTING BATO EAST", "PUTING BATO WEST", "PUTING KAHOY",
    "QUISUMBING", "SALONG", "SAN RAFAEL", "SINISIAN", "TAKLANG ANAK",
    "TALISAY", "TAMAYO", "TIMBAIN"
  ],
  "CALATAGAN": [
    "BAGONG SILANG", "BAHA", "BALIBAGO", "BALITOC", "BARANGAY 1 (POB.)",
    "BARANGAY 2 (POB.)", "BARANGAY 3 (POB.)", "BARANGAY 4 (POB.)", "BIGA",
    "BUCAL", "CARLOSA", "CARRETUNAN", "ENCARNACION", "GULOD", "HUKAY",
    "LUCSUHIN", "LUYA", "PARAISO", "QUILITISAN", "REAL", "SAMBUNGAN",
    "SANTA ANA", "TALIBAYOG", "TALISAY", "TANAGAN"
  ],
  "CUENCA": [
    "BALAGBAG", "BARANGAY 1 (POB.)", "BARANGAY 2 (POB.)", "BARANGAY 3 (POB.)",
    "BARANGAY 4 (POB.)", "BARANGAY 5 (POB.)", "BARANGAY 6 (POB.)",
    "BARANGAY 7 (POB.)", "BARANGAY 8 (POB.)", "BUNGAHAN", "CALUMAYIN",
    "DALIPIT EAST", "DALIPIT WEST", "DITA", "DON JUAN", "EMMANUEL",
    "IBABAO", "LABAC", "PINAGKAISAHAN", "SAN FELIPE", "SAN ISIDRO"
  ],
  "IBAAN": [
    "BAGO", "BALANGA", "BUNGAHAN", "CALAMIAS", "CATANDALA", "COLIAT",
    "DAYAPAN", "LAPU-LAPU", "LUCSUHIN", "MABALOR", "MALAININ", "MATALA",
    "MUNTING-TUBIG", "PALINDAN", "PANGAO", "PANGHAYAAN", "POBLACION",
    "QUILO", "SABANG", "SALABAN I", "SALABAN II", "SAN AGUSTIN",
    "SANDALAN", "SANTO NIÑO", "TALAIBON", "TULAY NA PATPAT"
  ],
  "LAUREL": [
    "AS-IS", "BALAKILONG", "BARANGAY 1 (POB.)", "BARANGAY 2 (POB.)",
    "BARANGAY 3 (POB.)", "BARANGAY 4 (POB.)", "BARANGAY 5 (POB.)",
    "BERINAYAN", "BUGAAN EAST", "BUGAAN WEST", "BUSO-BUSO", "DAYAP ITAAS",
    "GULOD", "J. LEVISTE", "MOLINETE", "NIYUGAN", "PALIPARAN",
    "SAN GABRIEL", "SAN GREGORIO", "SANTA MARIA", "TICUB"
  ],
  "LEMERY": [
    "ANAK-DAGAT", "ARUMAHAN", "AYAO-IYAO", "BAGONG POOK", "BAGONG SIKAT",
    "BALANGA", "BUKAL", "CAHILAN I", "CAHILAN II", "DAYAPAN",
    "DISTRICT I (POB.)", "DISTRICT II (POB.)", "DISTRICT III (POB.)",
    "DISTRICT IV (POB.)", "DITA", "GULOD", "LUCKY", "MAGUIHAN",
    "MAHABANG DAHILIG", "MAHAYAHAY", "MAIGSING DAHILIG", "MALIGAYA",
    "MALINIS", "MASALISI", "MATAAS NA BAYAN", "MATINGAIN I", "MATINGAIN II",
    "MAYASANG", "NIUGAN", "NONONG CASTO", "PALANAS", "PAYAPA IBABA",
    "PAYAPA ILAYA", "RIZAL", "SAMBAL IBABA", "SAMBAL ILAYA",
    "SAN ISIDRO IBABA", "SAN ISIDRO ITAAS", "SANGALANG", "SINISIAN EAST",
    "SINISIAN WEST", "TALAGA", "TUBIGAN", "TUBUAN", "WAWA IBABA", "WAWA ILAYA"
  ],
  "LIAN": [
    "BAGONG POOK", "BALIBAGO", "BARANGAY 1 (POB.)", "BARANGAY 2 (POB.)",
    "BARANGAY 3 (POB.)", "BARANGAY 4 (POB.)", "BARANGAY 5 (POB.)",
    "BINUBUSAN", "BUNGAHAN", "CUMBA", "HUMAYINGAN", "KAPITO",
    "LUMANIAG", "LUYAHAN", "MALARUHATAN", "MATABUNGKAY", "PRENZA",
    "PUTING-KAHOY", "SAN DIEGO"
  ]
};

// Get all municipalities/cities
export const BATANGAS_MUNICIPALITIES = Object.keys(BATANGAS_LOCATIONS).sort();

// Get barangays for a specific municipality
export const getBarangays = (municipality) => {
  return BATANGAS_LOCATIONS[municipality] || [];
};
