// Batangas Province locations extracted from AllLocationsPossible.json
// Region IV-A (CALABARZON) - Batangas Province

export const BATANGAS_LOCATIONS = {
  "AGONCILLO": [
    "ADIA", "BAGONG SIKAT", "BALANGON", "BANGIN", "BANYAGA", "BARIGON",
    "BILIBINWANG", "CORAL NA MUNTI", "GUITNA", "MABINI", "PAMIGA",
    "PANHULAN", "PANSIPIT", "POBLACION", "POOK", "SAN JACINTO",
    "SAN TEODORO", "SANTA CRUZ", "SANTO TOMAS", "SUBIC IBABA", "SUBIC ILAYA"
  ],
  "ALITAGTAG": [
    "BALAGBAG", "CONCEPCION", "CONCORDIA", "DALIPIT EAST", "DALIPIT WEST",
    "DOMINADOR EAST", "DOMINADOR WEST", "MUNLAWIN NORTE", "MUNLAWIN SUR",
    "MUZON PRIMERO", "MUZON SEGUNDO", "PINAGKURUSAN", "PING-AS",
    "POBLACION EAST", "POBLACION WEST", "SAN JOSE", "SAN JUAN", "SANTA CRUZ", "TADLAC"
  ],
  "BALAYAN": [
    "BACLARAN", "BARANGAY 1 (POB.)", "BARANGAY 2 (POB.)", "BARANGAY 3 (POB.)",
    "BARANGAY 4 (POB.)", "BARANGAY 5 (POB.)", "BARANGAY 6 (POB.)", "BARANGAY 7 (POB.)",
    "BARANGAY 8 (POB.)", "BARANGAY 9 (POB.)", "BARANGAY 10 (POB.)", "BARANGAY 11 (POB.)",
    "BARANGAY 12 (POB.)", "CALAN", "CALOOCAN", "CALZADA", "CANDA", "CARENAHAN",
    "CAYBUNGA", "CAYPONCE", "DALIG", "DAO", "DILAO", "DUHATAN", "DURUNGAO",
    "GIMALAS", "GUMAMELA", "LAGNAS", "LANATAN", "LANGGANGAN", "LUCBAN POOK",
    "LUCBAN PUTOL", "MAGABE", "MALALAY", "MUNTING TUBIG", "NAVOTAS",
    "PALIKPIKAN", "PATUGO", "POOC", "SAMBAT", "SAMPAGA", "SAN JUAN",
    "SAN PIRO", "SANTOL", "SUKOL", "TACTAC", "TALUDTUD", "TANGGOY"
  ],
  "BALETE": [
    "ALANGILAN", "CALAWIT", "LOOC", "MAGAPI", "MAKINA", "MALABANAN",
    "PALIGAWAN", "PALSARA", "POBLACION", "SALA", "SAMPALOCAN",
    "SAN SEBASTIAN", "SOLIS"
  ],
  "BATANGAS CITY": [
    "ALANGILAN", "BALAGTAS", "BALETE", "BANABA CENTER", "BANABA IBABA",
    "BANABA KANLURAN", "BANABA SILANGAN", "BARANGAY 1 (POB.)", "BARANGAY 2 (POB.)",
    "BARANGAY 3 (POB.)", "BARANGAY 4 (POB.)", "BARANGAY 5 (POB.)", "BARANGAY 6 (POB.)",
    "BARANGAY 7 (POB.)", "BARANGAY 8 (POB.)", "BARANGAY 9 (POB.)", "BARANGAY 10 (POB.)",
    "BARANGAY 11 (POB.)", "BARANGAY 12 (POB.)", "BARANGAY 13 (POB.)", "BARANGAY 14 (POB.)",
    "BARANGAY 15 (POB.)", "BARANGAY 16 (POB.)", "BARANGAY 17 (POB.)", "BARANGAY 18 (POB.)",
    "BARANGAY 19 (POB.)", "BARANGAY 20 (POB.)", "BARANGAY 21 (POB.)", "BARANGAY 22 (POB.)",
    "BARANGAY 23 (POB.)", "BARANGAY 24 (POB.)", "BILOGO", "BOLBOK", "BUKAL",
    "CALICANTO", "CATANDALA", "CONCEPCION", "CONDE ITAAS", "CONDE LABAK",
    "CUTA", "DALIG", "DELA PAZ", "DELA PAZ PULOT APLAYA", "DELA PAZ PULOT ITAAS",
    "DOMOCLAY", "DUMANTAY", "GULOD ITAAS", "GULOD LABAK", "HALIGUE KANLURAN",
    "HALIGUE SILANGAN", "ILIHAN", "KUMBA", "KUMINTANG IBABA", "KUMINTANG ILAYA",
    "LIBJO", "LIPONPON, ISLA VERDE", "MAAPAS", "MABACONG (MATOCO)",
    "MAHABANG DAHILIG", "MAHABANG PARANG", "MAHACOT KANLURAN", "MAHACOT SILANGAN",
    "MALALIM", "MALIBAYO", "MALITAM", "MARUCLAP", "PAGKILATAN",
    "PAHARANG KANLURAN", "PAHARANG SILANGAN", "PALLOCAN KANLURAN", "PALLOCAN SILANGAN",
    "PINAMUCAN", "PINAMUCAN IBABA", "PINAMUCAN SILANGAN", "SAMPAGA",
    "SAN AGAPITO, ISLA VERDE", "SAN AGUSTIN KANLURAN, ISLA VERDE",
    "SAN AGUSTIN SILANGAN, ISLA VERDE", "SAN ANDRES, ISLA VERDE",
    "SAN ANTONIO, ISLA VERDE", "SAN ISIDRO", "SAN JOSE SICO", "SAN MIGUEL",
    "SAN PEDRO", "SANTA CLARA", "SANTA RITA APLAYA", "SANTA RITA KARSADA",
    "SANTO DOMINGO", "SANTO NIÑO", "SIMLONG", "SIRANG LUPA", "SOROSORO IBABA",
    "SOROSORO ILAYA", "SOROSORO KARSADA", "TABANGAO AMBULONG",
    "TABANGAO APLAYA (TABANGAO PROPER)", "TABANGAO DAO", "TALAHIB PANDAYAN",
    "TALAHIB PAYAPA", "TALUMPOK KANLURAN", "TALUMPOK SILANGAN", "TINGA ITAAS",
    "TINGA LABAK", "TULO", "WAWA"
  ],
  "BAUAN": [
    "ALAGAO", "APLAYA", "AS-IS", "BAGONG SILANG", "BAGUILAWA", "BALAYONG",
    "BARANGAY I (POB.)", "BARANGAY II (POB.)", "BARANGAY III (POB.)",
    "BARANGAY IV (POB.)", "BOLO", "COLVO", "CUPANG", "DURUNGAO", "GULIBAY",
    "INICBULAN", "LOCLOC", "MAGALANG-GALANG", "MALINDIG", "MANALUPONG",
    "MANGHINAO PROPER", "MANGHINAO UNO", "NEW DANGLAYAN", "ORENSE", "PITUGO",
    "RIZAL", "SAMPAGUITA", "SAN AGUSTIN", "SAN ANDRES PROPER", "SAN ANDRES UNO",
    "SAN DIEGO", "SAN MIGUEL", "SAN PABLO", "SAN PEDRO", "SAN ROQUE",
    "SAN TEODORO", "SAN VICENTE", "SANTA MARIA", "SANTO DOMINGO", "SINALA"
  ],
  "CALACA": [
    "BACLAS", "BAGONG TUBIG", "BALIMBING", "BAMBANG", "BARANGAY 1 (POB.)",
    "BARANGAY 2 (POB.)", "BARANGAY 3 (POB.)", "BARANGAY 4 (POB.)",
    "BARANGAY 5 (POB.)", "BARANGAY 6 (POB.)", "BISAYA", "CAHIL", "CALANTAS",
    "CALUANGAN", "CAMASTILISAN", "CORAL NI BACAL", "CORAL NI LOPEZ (SUGOD)",
    "DACANLAO", "DILA", "LOMA", "LUMBANG CALZADA", "LUMBANG NA BATA",
    "LUMBANG NA MATANDA", "MADALUNOT", "MAKINA", "MATIPOK", "MUNTING CORAL",
    "NIYUGAN", "PANTAY", "PUTING BATO EAST", "PUTING BATO WEST", "PUTING KAHOY",
    "QUISUMBING", "SALONG", "SAN RAFAEL", "SINISIAN", "TAKLANG ANAK",
    "TALISAY", "TAMAYO", "TIMBAIN"
  ],
  "CALATAGAN": [
    "BAGONG SILANG", "BAHA", "BALIBAGO", "BALITOC", "BARANGAY 1 (POB.)",
    "BARANGAY 2 (POB.)", "BARANGAY 3 (POB.)", "BARANGAY 4 (POB.)", "BIGA",
    "BUCAL", "CARLOSA", "CARRETUNAN", "ENCARNACION", "GULOD", "HUKAY",
    "LUCSUHIN", "LUYA", "PARAISO", "QUILITISAN", "REAL", "SAMBUNGAN",
    "SANTA ANA", "TALIBAYOG", "TALISAY", "TANAGAN"
  ],
  "CUENCA": [
    "BALAGBAG", "BARANGAY 1 (POB.)", "BARANGAY 2 (POB.)", "BARANGAY 3 (POB.)",
    "BARANGAY 4 (POB.)", "BARANGAY 5 (POB.)", "BARANGAY 6 (POB.)",
    "BARANGAY 7 (POB.)", "BARANGAY 8 (POB.)", "BUNGAHAN", "CALUMAYIN",
    "DALIPIT EAST", "DALIPIT WEST", "DITA", "DON JUAN", "EMMANUEL",
    "IBABAO", "LABAC", "PINAGKAISAHAN", "SAN FELIPE", "SAN ISIDRO"
  ],
  "IBAAN": [
    "BAGO", "BALANGA", "BUNGAHAN", "CALAMIAS", "CATANDALA", "COLIAT",
    "DAYAPAN", "LAPU-LAPU", "LUCSUHIN", "MABALOR", "MALAININ", "MATALA",
    "MUNTING-TUBIG", "PALINDAN", "PANGAO", "PANGHAYAAN", "POBLACION",
    "QUILO", "SABANG", "SALABAN I", "SALABAN II", "SAN AGUSTIN",
    "SANDALAN", "SANTO NIÑO", "TALAIBON", "TULAY NA PATPAT"
  ],
  "LAUREL": [
    "AS-IS", "BALAKILONG", "BARANGAY 1 (POB.)", "BARANGAY 2 (POB.)",
    "BARANGAY 3 (POB.)", "BARANGAY 4 (POB.)", "BARANGAY 5 (POB.)",
    "BERINAYAN", "BUGAAN EAST", "BUGAAN WEST", "BUSO-BUSO", "DAYAP ITAAS",
    "GULOD", "J. LEVISTE", "MOLINETE", "NIYUGAN", "PALIPARAN",
    "SAN GABRIEL", "SAN GREGORIO", "SANTA MARIA", "TICUB"
  ],
  "LEMERY": [
    "ANAK-DAGAT", "ARUMAHAN", "AYAO-IYAO", "BAGONG POOK", "BAGONG SIKAT",
    "BALANGA", "BUKAL", "CAHILAN I", "CAHILAN II", "DAYAPAN",
    "DISTRICT I (POB.)", "DISTRICT II (POB.)", "DISTRICT III (POB.)",
    "DISTRICT IV (POB.)", "DITA", "GULOD", "LUCKY", "MAGUIHAN",
    "MAHABANG DAHILIG", "MAHAYAHAY", "MAIGSING DAHILIG", "MALIGAYA",
    "MALINIS", "MASALISI", "MATAAS NA BAYAN", "MATINGAIN I", "MATINGAIN II",
    "MAYASANG", "NIUGAN", "NONONG CASTO", "PALANAS", "PAYAPA IBABA",
    "PAYAPA ILAYA", "RIZAL", "SAMBAL IBABA", "SAMBAL ILAYA",
    "SAN ISIDRO IBABA", "SAN ISIDRO ITAAS", "SANGALANG", "SINISIAN EAST",
    "SINISIAN WEST", "TALAGA", "TUBIGAN", "TUBUAN", "WAWA IBABA", "WAWA ILAYA"
  ],
  "LIAN": [
    "BAGONG POOK", "BALIBAGO", "BARANGAY 1 (POB.)", "BARANGAY 2 (POB.)",
    "BARANGAY 3 (POB.)", "BARANGAY 4 (POB.)", "BARANGAY 5 (POB.)",
    "BINUBUSAN", "BUNGAHAN", "CUMBA", "HUMAYINGAN", "KAPITO",
    "LUMANIAG", "LUYAHAN", "MALARUHATAN", "MATABUNGKAY", "PRENZA",
    "PUTING-KAHOY", "SAN DIEGO"
  ],
  "LIPA CITY": [
    "ADYA", "ANILAO", "ANILAO-LABAC", "ANTIPOLO DEL NORTE", "ANTIPOLO DEL SUR",
    "BAGONG POOK", "BALINTAWAK", "BANAYBANAY", "BOLBOK", "BUGTONG NA PULO",
    "BULACNIN", "BULAKLAKAN", "CALAMIAS", "CUMBA", "DAGATAN", "DUHATAN",
    "HALANG", "INOSLUBAN", "KAYUMANGGI", "LATAG", "LODLOD", "LUMBANG",
    "MABINI", "MALAGONLONG", "MALITLIT", "MARAUOY", "MATAAS NA LUPA",
    "MUNTING PULO", "PAGOLINGIN BATA", "PAGOLINGIN EAST", "PAGOLINGIN WEST",
    "PANGAO", "PINAGKAWITAN", "PINAGTONGULAN", "PLARIDEL", "POBLACION",
    "PUSIL", "QUEZON", "RIZAL", "SABANG", "SAMPAGUITA", "SAN BENITO",
    "SAN CARLOS", "SAN CELESTINO", "SAN FRANCISCO", "SAN GUILLERMO",
    "SAN JOSE", "SAN LUCAS", "SAN SALVADOR", "SAN SEBASTIAN", "SANTO NIÑO",
    "SANTO TORIBIO", "SAPAC", "SICO", "TALISAY", "TAMBO", "TANGOB",
    "TANGUAY", "TIBIG", "TIPACAN", "ULANGO"
  ],
  "LOBO": [
    "APAR", "BAGONG SIKAT", "BALIBAGO", "BARANGAY 1 (POB.)", "BARANGAY 2 (POB.)",
    "BARANGAY 3 (POB.)", "BARANGAY 4 (POB.)", "BIGA", "BOCBOC", "BUYONG",
    "CALO", "FABRICA", "JAYBANGA", "LAGADLARIN", "MABILOG NA BUNDOK",
    "MALABRIGO", "NAGTALONGTONG", "NAGTOCTOC", "OLE", "PINAGHAWANAN",
    "SAN MIGUEL", "SAN NICOLAS", "SAWANG", "SOLOC", "TAYUMAN"
  ],
  "MABINI": [
    "ANILAO PROPER", "ANILAO EAST", "BAGALANGIT", "BALIBAGO", "BULACAN",
    "CALAMIAS", "DALAHICAN", "ESTRELLA", "GASANG", "LAUREL", "LIGAYA",
    "MAINAGA", "MAINIT", "MAIPIT", "MAJUBEN", "MALIMATOC I", "MALIMATOC II",
    "MUNTING CORAL", "NAGBALAYONG", "POBLACION", "PULANG LUPA", "PULONG ANAHAO",
    "PULONG BALIBAGUHAN", "PULONG NIOGAN", "SAGUING", "SAN FRANCISCO",
    "SAN JOSE", "SAN JUAN", "SANTA ANA", "SANTA MESA", "SANTO NIÑO",
    "SANTO TOMAS", "SOLOC", "TALAGA EAST", "TALAGA PROPER"
  ],
  "MALVAR": [
    "BAGONG POOK", "BILUCAO", "BULIHAN", "LUTA DEL NORTE", "LUTA DEL SUR",
    "POBLACION", "SAN ANDRES", "SAN FERNANDO", "SAN GREGORIO", "SAN JUAN",
    "SAN PEDRO I", "SAN PEDRO II", "SAN PIOQUINTO"
  ],
  "MATAAS NA KAHOY": [
    "BARANGAY I (POB.)", "BARANGAY II (POB.)", "BARANGAY III (POB.)",
    "BARANGAY IV (POB.)", "BUKAL", "CALINGATAN", "KINALAGLAGAN",
    "LOOB", "LUMANG LIPA", "MANGGAHAN", "NANGKAAN", "SAN SEBASTIAN",
    "SANTOL", "ULE"
  ],
  "NASUGBU": [
    "AGA", "BALAYTIGUI", "BANILAD", "BARANGAY 1 (POB.)", "BARANGAY 2 (POB.)",
    "BARANGAY 3 (POB.)", "BARANGAY 4 (POB.)", "BARANGAY 5 (POB.)",
    "BARANGAY 6 (POB.)", "BARANGAY 7 (POB.)", "BARANGAY 8 (POB.)",
    "BARANGAY 9 (POB.)", "BARANGAY 10 (POB.)", "BARANGAY 11 (POB.)",
    "BARANGAY 12 (POB.)", "BILARAN", "BUCANA", "BUNGAHAN", "BUTUCAN",
    "CALAYO", "CATANDAAN", "COGUNAN", "DAYAP", "KAYLAWAY", "KAYRILAW",
    "LATAG", "LOOC", "LUMBANGAN", "MALAPAD NA BATO", "MATAAS NA PULO",
    "MAUGAT EAST", "MAUGAT WEST", "MUNTING INDAN", "NATIPUAN",
    "PANTALAN", "PAPAYA", "PUTAT", "REPARO", "TALANGAN", "TUMALIM",
    "UTOD", "WAWA"
  ],
  "PADRE GARCIA": [
    "BANABA", "BANAYBANAY", "BAWI", "BILIBINWANG", "BUKAL", "CALAN",
    "CASTILLO", "CAWONGAN", "LUNA", "MABINI", "MANGGAS", "MARAUOY",
    "PANSOL", "PAYAPA", "POBLACION I-A", "POBLACION I-B", "POBLACION II-A",
    "POBLACION II-B", "QUILO-QUILO NORTE", "QUILO-QUILO SUR", "TANGOB"
  ],
  "ROSARIO": [
    "ALUPAY", "ANTIPOLO", "BAGONG POOK", "BALIBAGO", "BAYAWANG",
    "BULIHAN", "CACAWAN", "DILIMAN I", "DILIMAN II", "LANDAYAN",
    "LUCSUHIN", "LUMBANGAN", "MABATO", "MABUNGA", "NAMUNGA",
    "NASI I", "NASI II", "PIÑA", "POBLACION", "PUTINGKAHOY",
    "SAN CARLOS", "SAN IGNACIO", "SAN ISIDRO ITAAS", "SAN ISIDRO LABAK",
    "SAN JOSE", "SAN ROQUE", "TIQUIWAN"
  ],
  "SAN JOSE": [
    "ANUS", "APLICAYA", "AYA", "BAGONG POOK", "BANAYBANAY I", "BANAYBANAY II",
    "BIGAIN I", "BIGAIN II", "BIGAIN NORTE", "BIGAIN SUR", "CALANSAYAN",
    "DON LUIS", "GALAMAY-AMO", "LAPOLAPO I", "LAPOLAPO II", "LAPOLAPO III",
    "LUMIL", "MATUNGAW", "NANGKAAN", "PALANCA", "PINAGTUNG-ULAN",
    "POBLACION", "PULONG ANAHAO", "PULONG BULI", "SANTO CRISTO",
    "TAYSAN", "TINGA ITAAS", "TINGA LABAC"
  ],
  "SAN JUAN": [
    "ABUNG", "BALAGBAG", "BARUALTE", "BATAAN", "BUHAY NA TUBIG",
    "BULSA", "CALICANTO", "CALITCALIT", "CALUMNAYAN", "CATMON",
    "ESCRIBANO", "EXPANDING", "HUGOM", "IMELDA", "JANAOJANAO",
    "LAIYA-APLAYA", "LAIYA-IBABAO", "LAPOLAPO", "LIBATO", "LIPAHAN",
    "MABALANOY", "MARAYKIT", "MUZON", "NAGSAULAY", "NATUNUAN",
    "PALAHANAN I", "PALAHANAN II", "PINAGBAYANAN", "POBLACION",
    "POCTOL", "POOK NI KAPITAN", "POOK NI KULAS", "PULANGBATO",
    "PUTINGBUHANGIN", "QUILO-QUILO", "SAMPIRO", "SAN BENIGNO",
    "SAN ISIDRO", "SAPANGAN", "SUBUKIN", "TALAHIBAN I", "TALAHIBAN II"
  ],
  "SAN LUIS": [
    "BAGONG TUBIG", "BALITE", "BANOYO", "BULI", "CALUMPANG EAST",
    "CALUMPANG WEST", "DURUNGAO", "LEVISTE", "LOCLOC", "LUYA",
    "POBLACION EAST", "POBLACION SOUTH", "POBLACION WEST", "SAN ANTONIO",
    "SAN ISIDRO", "SAN JOSE", "SANTA MONICA", "SANTO NIÑO", "TALIBA",
    "TEJERO"
  ],
  "SAN NICOLAS": [
    "ALAS-AS", "BALANGON", "BANGIN", "BARANGAY 1 (POB.)", "BARANGAY 2 (POB.)",
    "BARANGAY 3 (POB.)", "BARANGAY 4 (POB.)", "BARANGAY 5 (POB.)",
    "BUHANGINAN", "CALANGAY", "دياديا", "LUNGIB", "MUNLAWIN",
    "PANDEÑO", "SAN ANDRES", "SANTA CRUZ", "SINTURISAN", "SOKOL"
  ],
  "SAN PASCUAL": [
    "ALALUM", "ANITONG", "BALIMBING", "BANABA", "BAYANAN", "DANGLAYAN",
    "DEL PILAR", "KAINGIN", "LAUREL", "MALAKING PULO", "NAG-IBA",
    "NATUNUAN NORTE", "NATUNUAN SUR", "PALSAHINGIN", "PILA", "POBLACION",
    "PONPON", "PULANGBATO", "RESPLANDOR", "SAN ANTONIO", "SAN MARIANO",
    "SAN MATEO", "SANTA ELENA", "SANTO NIÑO", "TABANGAO"
  ],
  "SANTA TERESITA": [
    "ANTIPOLO", "BIHIS", "BUROL", "CALAYAAN", "CALUMALA", "CUTANG CAWAYAN",
    "IRUKAN", "LUCONG BUNAK", "LUMBANGAN", "PACIFICO", "POBLACION",
    "POMBOK EAST", "POMBOK WEST", "SAMPA-SAMPA", "SINIPIAN", "SOLIS",
    "TAMAYO"
  ],
  "SANTO TOMAS": [
    "BARANGAY I (POB.)", "BARANGAY II (POB.)", "BARANGAY III (POB.)",
    "BARANGAY IV (POB.)", "SAN AGUSTIN", "SAN ANTONIO", "SAN BARTOLOME",
    "SAN FELIX", "SAN FERNANDO", "SAN FRANCISCO", "SAN ISIDRO NORTE",
    "SAN ISIDRO SUR", "SAN JOAQUIN", "SAN JOSE", "SAN JUAN",
    "SAN LUIS", "SAN MIGUEL", "SAN PABLO", "SAN PEDRO", "SAN RAFAEL",
    "SAN ROQUE", "SAN VICENTE", "SANTA ANA", "SANTA CLARA NORTE",
    "SANTA CLARA SUR", "SANTA CRUZ", "SANTA ELENA", "SANTA MARIA",
    "SANTIAGO", "SANTO NIÑO", "SANTO TOMAS"
  ],
  "TAAL": [
    "APACAY", "BALISONG", "BANADERO", "BANYAGA", "BARANGAY 1 (POB.)",
    "BARANGAY 2 (POB.)", "BARANGAY 3 (POB.)", "BARANGAY 4 (POB.)",
    "BARANGAY 5 (POB.)", "BARANGAY 6 (POB.)", "BIHIS", "BOLBOK",
    "BULI", "BUTONG", "CARASUCHE", "CAWIT", "CUBAMBA", "CULTIHAN",
    "GAHOL", "HALANG", "IMAMAWO", "LEYNES", "LIANG", "LUNTAL",
    "MIDDLE EARTH", "NATIPUAN", "NIOGAN", "NOWERO", "PANSOL",
    "QUILING", "SAMBAT", "SAN GUILLERMO", "SANTOL", "SEIRAN",
    "SINTURISAN", "TIERRA ALTA", "TIERRA NUEVA", "TUMAWAY"
  ],
  "TALISAY": [
    "ABAN", "BALAS", "BANGA", "BANGขO", "BUCO", "BULIHAN",
    "CALOOCAN", "LEYNES", "MARIA PAZ", "MIRANDA", "POBLACION",
    "QUILING", "SAN GUILLERMO", "SANTA MARIA", "TRANCA", "TUMAWAY"
  ],
  "TANAUAN CITY": [
    "ALTURA BATA", "ALTURA MATANDA", "ALTURA-SOUTH", "AMBULONG",
    "BAGBAG", "BAGUMBAYAN", "BALELE", "BANADERO", "BANJO EAST",
    "BANJO LAUREL", "BANJO WEST", "BILOG-BILOG", "BOOT", "CALE",
    "DARASA", "GONZALES", "HIDALGO", "JANOPOL", "JANOPOL ORIENTAL",
    "LAUREL", "LUYOS", "MABINI", "MALAKING PULO", "MARIA PAZ",
    "MAUGAT", "MONTANA", "NATATAS", "PAGASPAS", "PANTAY MATANDA",
    "PANTAY NA MATANDA", "POBLACION BARANGAY 1", "POBLACION BARANGAY 2",
    "POBLACION BARANGAY 3", "POBLACION BARANGAY 4", "POBLACION BARANGAY 5",
    "POBLACION BARANGAY 6", "POBLACION BARANGAY 7", "SAMBAT",
    "SAN JOSE", "САНТА CLARA", "SANTOL", "SUPLANG", "TALAGA",
    "TINURIK", "TRAPICHE", "ULANGO", "WAWA"
  ],
  "TAYSAN": [
    "BACAO", "BILOGO", "BUKAL", "DAGATAN", "GUINHAWA", "LAUREL",
    "MABAYABAS", "MAHANADIONG", "MATAAS NA LUPA", "PALO", "PANGHAYAAN",
    "PINAGBAYANAN", "POBLACION EAST", "POBLACION WEST", "SAN ISIDRO",
    "SAN MARCELINO", "SANTO NIÑO"
  ],
  "TINGLOY": [
    "CORONA", "GAMAO", "MAHABANG GULOD", "PISA", "POBLACION",
    "SAN ISIDRO", "SAN JOSE", "SAN JUAN", "SAN PEDRO", "SANTA ANA"
  ],
  "TUY": [
    "ABABU", "BURGOS", "DALIMA", "DOS HERMANAS", "JAVIER",
    "LUNA", "LUNTAL", "MAGAHIS", "MALIBU", "MATAYWANAC",
    "OLE", "PALSAHINGIN", "POBLACION", "PUTOL", "RILLO",
    "SABANG", "SAN JOSE", "SANTA CLARA", "TALON", "TOONG"
  ]
};

// Get all municipalities/cities
export const BATANGAS_MUNICIPALITIES = Object.keys(BATANGAS_LOCATIONS).sort();

// Get barangays for a specific municipality
export const getBarangays = (municipality) => {
  return BATANGAS_LOCATIONS[municipality] || [];
};
